name = "dinkdonkbot"
main = "./src/server.ts"
compatibility_date = "2024-01-01"
kv_namespaces = [ { binding = "KV", id = "2368012e59c642ada32014c95609dd1b" } ]
compatibility_flags = [ "nodejs_compat" ]

[triggers]
crons = [ "0 0 * * *" ]

[[d1_databases]]
binding = "DB"
database_name = "dinkdonk"
database_id = "3221ff85-9afb-4081-bb4d-6876473c6dd7"
migrations_dir = "src/database/migrations"

[placement]
mode = "smart"

[observability]
enabled = true

# [secrets]
# DISCORD_TOKEN
# DISCORD_PUBLIC_KEY
# DISCORD_APPLICATION_ID
# TWITCH_CLIENT_ID
# TWITCH_CLIENT_SECRET
# TWITCH_EVENT_SECRET
# WEBHOOK_URL

